import os

# LINE Messaging API
LINE_CHANNEL_SECRET = os.environ["LINE_CHANNEL_SECRET"]
LINE_CHANNEL_ACCESS_TOKEN = os.environ["LINE_CHANNEL_ACCESS_TOKEN"]

# Google Gemini
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
GEMINI_MODEL = "gemini-3-flash-preview"

# アプリケーション設定
LINE_REPLY_MAX_LENGTH = 5000
CONVERSATION_HISTORY_MAX_TURNS = 10
CONVERSATION_HISTORY_TTL = 3600  # 秒 (1時間)
MAX_USERS_IN_MEMORY = 1000
